//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelOfFortune.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheelOfFortune.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        public static string MainWindow_EntriesTabItem_HeaderText {
            get {
                return ResourceManager.GetString("MainWindow_EntriesTabItem_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string MainWindow_HistoryDataGrid_ResultHeader {
            get {
                return ResourceManager.GetString("MainWindow_HistoryDataGrid_ResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string MainWindow_HistoryDataGrid_TimestampHeader {
            get {
                return ResourceManager.GetString("MainWindow_HistoryDataGrid_TimestampHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string MainWindow_HistoryTabItem_HeaderText {
            get {
                return ResourceManager.GetString("MainWindow_HistoryTabItem_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from clipboard.
        /// </summary>
        public static string MainWindow_ImportFromClipboardButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_ImportFromClipboardButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle items.
        /// </summary>
        public static string MainWindow_ShuffleItemsButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_ShuffleItemsButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter one splice per line.
        /// </summary>
        public static string MainWindow_SlicesTextBox_Hint {
            get {
                return ResourceManager.GetString("MainWindow_SlicesTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin.
        /// </summary>
        public static string MainWindow_SpinButton_Content {
            get {
                return ResourceManager.GetString("MainWindow_SpinButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing from clipboard will overwrite your current slices. Do you want to continue?.
        /// </summary>
        public static string OverwriteSlicesDialog_ContentTextBlock_Text {
            get {
                return ResourceManager.GetString("OverwriteSlicesDialog_ContentTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite slices?.
        /// </summary>
        public static string OverwriteSlicesDialog_HeaderTextBlock_Text {
            get {
                return ResourceManager.GetString("OverwriteSlicesDialog_HeaderTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel result.
        /// </summary>
        public static string ResultDialog_HeaderTextBlock_Text {
            get {
                return ResourceManager.GetString("ResultDialog_HeaderTextBlock_Text", resourceCulture);
            }
        }
    }
}
